default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: rails_modern_app_development
  username: root
  password: <%= Rails.application.credentials[:database_password] %>
 
test:
  <<: *default
  database: rails_modern_app_test
  username: root
  password: <%= Rails.application.credentials[:database_password] %>

production:
  <<: *default
  database: rails_modern_app_production
  username: modern_app
  password: <%= Rails.application.credentials[:database_password] %>
